//! FraudShield Uganda - WebAssembly Fraud Detection Engine
//!
//! This module provides high-performance fraud detection algorithms
//! compiled to WebAssembly for browser-based execution.

use wasm_bindgen::prelude::*;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use regex::Regex;

// Enable better error messages in debug builds
#[cfg(feature = "console_error_panic_hook")]
pub fn set_panic_hook() {
    console_error_panic_hook::set_once();
}

// ============================================
// DATA STRUCTURES
// ============================================

/// A single loan record with standardized fields
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct LoanRecord {
    pub loan_id: Option<String>,
    pub borrower_id: Option<String>,
    pub borrower_name: Option<String>,
    pub phone: Option<String>,
    pub national_id: Option<String>,
    pub amount: Option<f64>,
    pub loan_date: Option<String>,
    pub approval_time: Option<String>,
    pub officer_id: Option<String>,
    pub officer_name: Option<String>,
    pub branch: Option<String>,
    pub status: Option<String>,
    pub guarantor_name: Option<String>,
    pub guarantor_phone: Option<String>,
    pub interest_rate: Option<f64>,
    pub term_months: Option<i32>,
    pub purpose: Option<String>,
    pub address: Option<String>,
}

/// A fraud alert generated by the detection engine
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FraudAlert {
    pub alert_type: String,
    pub severity: String,
    pub title: String,
    pub description: String,
    pub amount_at_risk: f64,
    pub officer_id: Option<String>,
    pub loan_ids: Vec<String>,
    pub details: serde_json::Value,
}

/// Officer statistics for risk analysis
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct OfficerStats {
    pub officer_id: String,
    pub name: String,
    pub loan_count: u32,
    pub total_amount: f64,
    pub alert_count: u32,
    pub z_score: f64,
    pub risk_score: u32,
}

/// Column mapping detection result
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ColumnMapping {
    pub original_column: String,
    pub mapped_field: Option<String>,
    pub confidence: u32,
    pub detection_method: String,
}

/// Analysis summary statistics
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct AnalysisSummary {
    pub total_records: u32,
    pub critical_alerts: u32,
    pub high_alerts: u32,
    pub medium_alerts: u32,
    pub low_alerts: u32,
    pub risk_score: u32,
}

/// Complete analysis results
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AnalysisResults {
    pub summary: AnalysisSummary,
    pub alerts: Vec<FraudAlert>,
    pub officers: Vec<OfficerStats>,
}

// ============================================
// WASM EXPORTS - MAIN API
// ============================================

/// Initialize the WebAssembly module
#[wasm_bindgen(start)]
pub fn init() {
    #[cfg(feature = "console_error_panic_hook")]
    set_panic_hook();
}

/// Parse CSV data and return as JSON array
#[wasm_bindgen]
pub fn parse_csv(csv_content: &str) -> String {
    let mut records: Vec<HashMap<String, String>> = Vec::new();
    let mut lines = csv_content.lines();

    // Get headers from first line
    let headers: Vec<String> = match lines.next() {
        Some(header_line) => parse_csv_line(header_line),
        None => return "[]".to_string(),
    };

    // Parse data rows
    for line in lines {
        if line.trim().is_empty() {
            continue;
        }
        let values = parse_csv_line(line);
        let mut record: HashMap<String, String> = HashMap::new();

        for (i, header) in headers.iter().enumerate() {
            let value = values.get(i).cloned().unwrap_or_default();
            record.insert(header.clone(), value);
        }
        records.push(record);
    }

    serde_json::to_string(&records).unwrap_or_else(|_| "[]".to_string())
}

/// Detect column mappings from raw data JSON
#[wasm_bindgen]
pub fn detect_columns(raw_data_json: &str) -> String {
    let data: Vec<HashMap<String, serde_json::Value>> = match serde_json::from_str(raw_data_json) {
        Ok(d) => d,
        Err(_) => return "[]".to_string(),
    };

    if data.is_empty() {
        return "[]".to_string();
    }

    let columns: Vec<String> = data[0].keys().cloned().collect();
    let mut mappings: Vec<ColumnMapping> = Vec::new();
    let mut used_fields: std::collections::HashSet<String> = std::collections::HashSet::new();

    // Collect all potential mappings with scores
    let mut all_detections: Vec<(String, String, u32, String)> = Vec::new();

    for col in &columns {
        if let Some((field, confidence, method)) = detect_column_type(col, &data) {
            all_detections.push((col.clone(), field, confidence, method));
        }
    }

    // Sort by confidence descending
    all_detections.sort_by(|a, b| b.2.cmp(&a.2));

    // Assign mappings, avoiding duplicates
    for (col, field, confidence, method) in all_detections {
        if !used_fields.contains(&field) {
            mappings.push(ColumnMapping {
                original_column: col,
                mapped_field: Some(field.clone()),
                confidence,
                detection_method: method,
            });
            used_fields.insert(field);
        }
    }

    // Add unmapped columns
    for col in &columns {
        if !mappings.iter().any(|m| m.original_column == *col) {
            mappings.push(ColumnMapping {
                original_column: col.clone(),
                mapped_field: None,
                confidence: 0,
                detection_method: "none".to_string(),
            });
        }
    }

    serde_json::to_string(&mappings).unwrap_or_else(|_| "[]".to_string())
}

/// Run fraud analysis on mapped data
#[wasm_bindgen]
pub fn analyze_fraud(mapped_data_json: &str) -> String {
    let data: Vec<LoanRecord> = match serde_json::from_str(mapped_data_json) {
        Ok(d) => d,
        Err(_) => return "{\"error\": \"Failed to parse data\"}".to_string(),
    };

    if data.is_empty() {
        return "{\"error\": \"No data to analyze\"}".to_string();
    }

    let mut alerts: Vec<FraudAlert> = Vec::new();
    let mut officer_stats: HashMap<String, OfficerStats> = HashMap::new();

    // Run detection algorithms
    detect_ghost_loans(&data, &mut alerts);
    detect_loan_stacking(&data, &mut alerts);
    detect_officer_anomalies(&data, &mut alerts, &mut officer_stats);
    detect_timing_anomalies(&data, &mut alerts);
    detect_amount_anomalies(&data, &mut alerts);

    // Calculate summary
    let mut summary = AnalysisSummary {
        total_records: data.len() as u32,
        ..Default::default()
    };

    for alert in &alerts {
        match alert.severity.as_str() {
            "CRITICAL" => summary.critical_alerts += 1,
            "HIGH" => summary.high_alerts += 1,
            "MEDIUM" => summary.medium_alerts += 1,
            _ => summary.low_alerts += 1,
        }

        // Track officer involvement
        if let Some(ref officer_id) = alert.officer_id {
            if let Some(stats) = officer_stats.get_mut(officer_id) {
                stats.alert_count += 1;
            }
        }
    }

    // Calculate risk score
    summary.risk_score = calculate_risk_score(&alerts);

    // Calculate officer risk scores
    let mut officers: Vec<OfficerStats> = officer_stats.into_values().collect();
    for officer in &mut officers {
        officer.risk_score = ((officer.alert_count * 10) as f64 +
            if officer.z_score > 2.0 { 30.0 } else { 0.0 }).min(100.0) as u32;
    }
    officers.sort_by(|a, b| b.risk_score.cmp(&a.risk_score));

    let results = AnalysisResults {
        summary,
        alerts,
        officers,
    };

    serde_json::to_string(&results).unwrap_or_else(|_| "{\"error\": \"Serialization failed\"}".to_string())
}

/// Generate sample data for testing
#[wasm_bindgen]
pub fn generate_sample_data(num_loans: u32) -> String {
    let first_names = ["John", "Mary", "Peter", "Grace", "David", "Sarah", "James", "Agnes", "Robert", "Florence"];
    let last_names = ["Mukasa", "Nakato", "Ssemakula", "Nambi", "Okello", "Akello", "Wasswa", "Babirye", "Kato", "Nalongo"];
    let officers = ["OFF001", "OFF002", "OFF003", "OFF004", "OFF005"];
    let branches = ["Kampala Central", "Entebbe", "Jinja", "Mbarara", "Gulu"];
    let statuses = ["active", "active", "active", "completed", "defaulted"];

    // Simple pseudo-random generator (for deterministic results)
    let mut seed: u64 = 12345;
    let mut rng = || -> f64 {
        seed = seed.wrapping_mul(1103515245).wrapping_add(12345);
        ((seed >> 16) & 0x7fff) as f64 / 32768.0
    };

    // Create fraud phone numbers
    let mut fraud_phones: Vec<String> = Vec::new();
    for _ in 0..5 {
        let phone = format!("07{}", (rng() * 90000000.0 + 10000000.0) as u64);
        fraud_phones.push(phone);
    }

    let mut records: Vec<HashMap<String, serde_json::Value>> = Vec::new();

    for i in 0..num_loans {
        let is_fraud = rng() < 0.05;
        let is_ghost = is_fraud && rng() < 0.5;
        let is_stacking = is_fraud && !is_ghost && rng() < 0.5;

        let hour = if is_fraud && !is_ghost && !is_stacking {
            if rng() < 0.5 {
                (rng() * 5.0) as u32
            } else {
                22 + (rng() * 3.0) as u32
            }
        } else {
            8 + (rng() * 10.0) as u32
        };

        let first_name = first_names[(rng() * first_names.len() as f64) as usize];
        let last_name = last_names[(rng() * last_names.len() as f64) as usize];

        let phone = if is_ghost {
            fraud_phones[(rng() * fraud_phones.len() as f64) as usize].clone()
        } else {
            format!("07{}", (rng() * 90000000.0 + 10000000.0) as u64)
        };

        let borrower_id = if is_stacking {
            format!("MBR{:04}", i / 3)
        } else {
            format!("MBR{:04}", i + 1)
        };

        let officer_id = if is_fraud {
            officers[0].to_string()
        } else {
            officers[(rng() * officers.len() as f64) as usize].to_string()
        };

        let month = (rng() * 12.0) as u32 + 1;
        let day = (rng() * 28.0) as u32 + 1;

        let mut record: HashMap<String, serde_json::Value> = HashMap::new();
        record.insert("loan_id".to_string(), serde_json::json!(format!("LN{:05}", i + 1)));
        record.insert("borrower_id".to_string(), serde_json::json!(borrower_id));
        record.insert("borrower_name".to_string(), serde_json::json!(format!("{} {}", first_name, last_name)));
        record.insert("phone".to_string(), serde_json::json!(phone));
        record.insert("amount".to_string(), serde_json::json!((rng() * 4000000.0 + 500000.0) as u64));
        record.insert("loan_date".to_string(), serde_json::json!(format!("2024-{:02}-{:02}", month, day)));
        record.insert("approval_time".to_string(), serde_json::json!(format!("{:02}:{:02}", hour, (rng() * 60.0) as u32)));
        record.insert("officer_id".to_string(), serde_json::json!(officer_id));
        record.insert("branch".to_string(), serde_json::json!(branches[(rng() * branches.len() as f64) as usize]));
        record.insert("status".to_string(), serde_json::json!(statuses[(rng() * statuses.len() as f64) as usize]));

        records.push(record);
    }

    serde_json::to_string(&records).unwrap_or_else(|_| "[]".to_string())
}

/// Calculate string similarity (Levenshtein-based)
#[wasm_bindgen]
pub fn string_similarity(s1: &str, s2: &str) -> f64 {
    levenshtein_similarity(s1, s2)
}

// ============================================
// INTERNAL FUNCTIONS - COLUMN DETECTION
// ============================================

/// Standard field name variations for matching
fn get_name_variations() -> HashMap<&'static str, Vec<&'static str>> {
    let mut variations: HashMap<&str, Vec<&str>> = HashMap::new();

    variations.insert("loan_id", vec![
        "loan_id", "loanid", "loan_no", "loan_number", "loan_ref", "reference",
        "loan_reference", "contract_id", "contract_no", "application_id",
        "disbursement_id", "txn_id", "transaction_id", "id", "ref_no"
    ]);

    variations.insert("borrower_id", vec![
        "borrower_id", "borrowerid", "member_id", "memberid", "client_id",
        "clientid", "customer_id", "customerid", "member_no", "member_number",
        "client_no", "account_no", "account_number", "sacco_no"
    ]);

    variations.insert("borrower_name", vec![
        "borrower_name", "borrowername", "name", "full_name", "fullname",
        "member_name", "membername", "client_name", "clientname",
        "customer_name", "customername", "applicant_name", "applicant"
    ]);

    variations.insert("phone", vec![
        "phone", "phone_number", "phonenumber", "mobile", "mobile_number",
        "mobilenumber", "telephone", "tel", "contact", "contact_number",
        "cell", "cellphone", "phone_no", "tel_no", "mobile_no"
    ]);

    variations.insert("national_id", vec![
        "national_id", "nationalid", "national_id_no", "nin", "id_no",
        "id_number", "idno", "national_identification", "id_card",
        "identification", "nid", "govt_id", "government_id"
    ]);

    variations.insert("amount", vec![
        "amount", "loan_amount", "loanamount", "principal", "principal_amount",
        "disbursed_amount", "disbursement", "approved_amount", "requested_amount",
        "credit_amount", "facility_amount", "sum", "total", "value"
    ]);

    variations.insert("loan_date", vec![
        "loan_date", "loandate", "disbursement_date", "date_disbursed",
        "issue_date", "created_date", "application_date", "approved_date",
        "date", "transaction_date", "txn_date", "start_date"
    ]);

    variations.insert("approval_time", vec![
        "approval_time", "time", "created_at", "timestamp", "datetime",
        "approved_time", "creation_time", "entry_time"
    ]);

    variations.insert("officer_id", vec![
        "officer_id", "officerid", "loan_officer_id", "staff_id", "staffid",
        "employee_id", "employeeid", "user_id", "userid", "approved_by",
        "created_by", "processed_by", "agent_id", "agent_code"
    ]);

    variations.insert("officer_name", vec![
        "officer_name", "officername", "loan_officer", "loanofficer",
        "staff_name", "staffname", "approved_by_name", "agent_name"
    ]);

    variations.insert("branch", vec![
        "branch", "branch_name", "branchname", "branch_id", "branchid",
        "branch_code", "location", "office", "center", "unit"
    ]);

    variations.insert("status", vec![
        "status", "loan_status", "loanstatus", "state", "current_status",
        "account_status", "disbursement_status"
    ]);

    variations
}

fn detect_column_type(col_name: &str, data: &[HashMap<String, serde_json::Value>]) -> Option<(String, u32, String)> {
    let col_lower = col_name.to_lowercase().replace(|c: char| !c.is_alphanumeric(), "_");
    let variations = get_name_variations();

    // Get sample values
    let sample: Vec<String> = data.iter()
        .take(100)
        .filter_map(|row| row.get(col_name))
        .filter_map(|v| match v {
            serde_json::Value::String(s) => Some(s.clone()),
            serde_json::Value::Number(n) => Some(n.to_string()),
            _ => None,
        })
        .filter(|s| !s.is_empty())
        .collect();

    let mut best_match: Option<String> = None;
    let mut best_score: u32 = 0;
    let mut detection_method = "none".to_string();

    // Method 1: Name matching
    for (field, vars) in &variations {
        for var in vars {
            // Exact match
            if col_lower == *var {
                return Some((field.to_string(), 100, "exact_match".to_string()));
            }

            // Contains match
            if col_lower.contains(var) || var.contains(&col_lower.as_str()) {
                let score = 85;
                if score > best_score {
                    best_score = score;
                    best_match = Some(field.to_string());
                    detection_method = "name_match".to_string();
                }
            }

            // Fuzzy match
            let similarity = levenshtein_similarity(&col_lower, var);
            if similarity > 0.7 {
                let score = (similarity * 100.0) as u32;
                if score > best_score {
                    best_score = score;
                    best_match = Some(field.to_string());
                    detection_method = "fuzzy_match".to_string();
                }
            }
        }
    }

    // Method 2: Pattern detection
    if !sample.is_empty() {
        if let Some((field, confidence)) = detect_by_pattern(&sample) {
            if confidence > best_score {
                best_score = confidence;
                best_match = Some(field);
                detection_method = "pattern".to_string();
            }
        }
    }

    // Method 3: Statistical detection
    if best_match.is_none() && !sample.is_empty() {
        if let Some((field, confidence)) = detect_by_statistics(&sample) {
            if confidence > best_score {
                best_score = confidence;
                best_match = Some(field);
                detection_method = "statistics".to_string();
            }
        }
    }

    if best_score > 40 {
        best_match.map(|field| (field, best_score, detection_method))
    } else {
        None
    }
}

fn detect_by_pattern(sample: &[String]) -> Option<(String, u32)> {
    // Phone number patterns
    let phone_regex = Regex::new(r"^(\+?256|0)?[0-9]{9}$").ok()?;
    let phone_matches = sample.iter()
        .filter(|s| phone_regex.is_match(&s.replace([' ', '-', '(', ')'], "")))
        .count();
    if phone_matches as f64 / sample.len() as f64 > 0.7 {
        return Some(("phone".to_string(), 90));
    }

    // National ID patterns (Uganda NIN)
    let nin_regex = Regex::new(r"^[A-Z]{2}\d{13}[A-Z0-9]$").ok()?;
    let nin_matches = sample.iter()
        .filter(|s| nin_regex.is_match(&s.to_uppercase().replace([' ', '-'], "")))
        .count();
    if nin_matches as f64 / sample.len() as f64 > 0.7 {
        return Some(("national_id".to_string(), 92));
    }

    // Date patterns
    let date_regex = Regex::new(r"^\d{4}-\d{2}-\d{2}$|^\d{2}/\d{2}/\d{4}$").ok()?;
    let date_matches = sample.iter()
        .filter(|s| date_regex.is_match(s))
        .count();
    if date_matches as f64 / sample.len() as f64 > 0.7 {
        return Some(("loan_date".to_string(), 85));
    }

    // Time patterns
    let time_regex = Regex::new(r"^\d{2}:\d{2}(:\d{2})?$").ok()?;
    let time_matches = sample.iter()
        .filter(|s| time_regex.is_match(s))
        .count();
    if time_matches as f64 / sample.len() as f64 > 0.7 {
        return Some(("approval_time".to_string(), 80));
    }

    // Amount patterns (formatted numbers with commas)
    let amount_regex = Regex::new(r"^\d{1,3}(,\d{3})+(\.\d{2})?$").ok()?;
    let amount_matches = sample.iter()
        .filter(|s| amount_regex.is_match(s))
        .count();
    if amount_matches as f64 / sample.len() as f64 > 0.7 {
        return Some(("amount".to_string(), 85));
    }

    None
}

fn detect_by_statistics(sample: &[String]) -> Option<(String, u32)> {
    // Check if numeric
    let numeric_sample: Vec<f64> = sample.iter()
        .filter_map(|s| s.replace(',', "").parse::<f64>().ok())
        .collect();

    if numeric_sample.len() as f64 / sample.len() as f64 > 0.9 {
        let mean = numeric_sample.iter().sum::<f64>() / numeric_sample.len() as f64;
        let min = numeric_sample.iter().cloned().fold(f64::INFINITY, f64::min);
        let max = numeric_sample.iter().cloned().fold(f64::NEG_INFINITY, f64::max);

        // Amount detection: large positive numbers
        if min >= 0.0 && mean > 100000.0 {
            return Some(("amount".to_string(), 75));
        }

        // Interest rate: 0-100 range
        if min >= 0.0 && max <= 100.0 && mean < 50.0 {
            return Some(("interest_rate".to_string(), 60));
        }

        // Term months: small positive integers
        if min >= 1.0 && max <= 360.0 {
            return Some(("term_months".to_string(), 55));
        }
    }

    // Check for unique IDs
    let unique: std::collections::HashSet<&String> = sample.iter().collect();
    if unique.len() as f64 / sample.len() as f64 > 0.95 {
        if sample.get(0).map(|s| s.len()).unwrap_or(0) < 15 {
            return Some(("loan_id".to_string(), 60));
        }
    }

    // Check for names (2+ words, mostly alphabetic)
    let name_regex = Regex::new(r"^[A-Za-z]+\s+[A-Za-z]+").ok()?;
    let name_matches = sample.iter()
        .filter(|s| name_regex.is_match(s))
        .count();
    if name_matches as f64 / sample.len() as f64 > 0.7 {
        return Some(("borrower_name".to_string(), 70));
    }

    // Check for status keywords
    let status_keywords = ["active", "inactive", "paid", "closed", "pending",
        "approved", "rejected", "defaulted", "completed", "disbursed", "overdue"];
    let status_matches = sample.iter()
        .filter(|s| status_keywords.iter().any(|k| s.to_lowercase().contains(k)))
        .count();
    if status_matches as f64 / sample.len() as f64 > 0.5 {
        return Some(("status".to_string(), 80));
    }

    None
}

// ============================================
// INTERNAL FUNCTIONS - FRAUD DETECTION
// ============================================

fn detect_ghost_loans(data: &[LoanRecord], alerts: &mut Vec<FraudAlert>) {
    let mut phone_counts: HashMap<String, Vec<&LoanRecord>> = HashMap::new();

    for record in data {
        if let Some(ref phone) = record.phone {
            if !phone.is_empty() {
                phone_counts.entry(phone.clone()).or_default().push(record);
            }
        }
    }

    for (phone, records) in phone_counts {
        if records.len() > 1 {
            let total_amount: f64 = records.iter()
                .filter_map(|r| r.amount)
                .sum();

            let loan_ids: Vec<String> = records.iter()
                .filter_map(|r| r.loan_id.clone())
                .collect();

            let details: Vec<serde_json::Value> = records.iter()
                .map(|r| serde_json::json!({
                    "loan_id": r.loan_id,
                    "borrower": r.borrower_name,
                    "amount": r.amount
                }))
                .collect();

            alerts.push(FraudAlert {
                alert_type: "GHOST_LOAN".to_string(),
                severity: if records.len() >= 4 { "CRITICAL".to_string() } else { "HIGH".to_string() },
                title: "Duplicate Phone Number Detected".to_string(),
                description: format!("Phone {} appears in {} different loans", phone, records.len()),
                amount_at_risk: total_amount,
                officer_id: records.first().and_then(|r| r.officer_id.clone()),
                loan_ids,
                details: serde_json::json!(details),
            });
        }
    }
}

fn detect_loan_stacking(data: &[LoanRecord], alerts: &mut Vec<FraudAlert>) {
    let mut borrower_date_map: HashMap<String, Vec<&LoanRecord>> = HashMap::new();

    for record in data {
        if let (Some(ref borrower_id), Some(ref date)) = (&record.borrower_id, &record.loan_date) {
            let key = format!("{}-{}", borrower_id, date);
            borrower_date_map.entry(key).or_default().push(record);
        }
    }

    for (_, records) in borrower_date_map {
        if records.len() > 1 {
            let total_amount: f64 = records.iter()
                .filter_map(|r| r.amount)
                .sum();

            let loan_ids: Vec<String> = records.iter()
                .filter_map(|r| r.loan_id.clone())
                .collect();

            alerts.push(FraudAlert {
                alert_type: "LOAN_STACKING".to_string(),
                severity: "HIGH".to_string(),
                title: "Multiple Loans Same Day".to_string(),
                description: format!("Borrower received {} loans on same date, total UGX {:.0}",
                    records.len(), total_amount),
                amount_at_risk: total_amount,
                officer_id: records.first().and_then(|r| r.officer_id.clone()),
                loan_ids,
                details: serde_json::json!(records),
            });
        }
    }
}

fn detect_officer_anomalies(
    data: &[LoanRecord],
    alerts: &mut Vec<FraudAlert>,
    officer_stats: &mut HashMap<String, OfficerStats>
) {
    // Build officer statistics
    for record in data {
        let officer_id = record.officer_id.clone().unwrap_or_else(|| "Unknown".to_string());
        let officer_name = record.officer_name.clone().unwrap_or_else(|| officer_id.clone());
        let amount = record.amount.unwrap_or(0.0);

        let stats = officer_stats.entry(officer_id.clone()).or_insert(OfficerStats {
            officer_id: officer_id.clone(),
            name: officer_name,
            ..Default::default()
        });

        stats.loan_count += 1;
        stats.total_amount += amount;
    }

    // Calculate z-scores
    let counts: Vec<f64> = officer_stats.values().map(|s| s.loan_count as f64).collect();
    if counts.is_empty() {
        return;
    }

    let mean = counts.iter().sum::<f64>() / counts.len() as f64;
    let variance = counts.iter().map(|c| (c - mean).powi(2)).sum::<f64>() / counts.len() as f64;
    let std_dev = variance.sqrt();

    for stats in officer_stats.values_mut() {
        if std_dev > 0.0 {
            stats.z_score = (stats.loan_count as f64 - mean) / std_dev;
        }

        // Generate alert for anomalous officers
        if stats.z_score > 2.0 {
            alerts.push(FraudAlert {
                alert_type: "OFFICER_ANOMALY".to_string(),
                severity: if stats.z_score > 3.0 { "HIGH".to_string() } else { "MEDIUM".to_string() },
                title: "Unusual Officer Volume".to_string(),
                description: format!("Officer {} processed {} loans ({:.1} std from avg)",
                    stats.name, stats.loan_count, stats.z_score),
                amount_at_risk: stats.total_amount * 0.1,
                officer_id: Some(stats.officer_id.clone()),
                loan_ids: vec![],
                details: serde_json::json!({
                    "officer_name": stats.name,
                    "loan_count": stats.loan_count,
                    "z_score": stats.z_score
                }),
            });
        }
    }
}

fn detect_timing_anomalies(data: &[LoanRecord], alerts: &mut Vec<FraudAlert>) {
    for record in data {
        if let Some(ref time) = record.approval_time {
            if let Some(hour) = time.split(':').next().and_then(|h| h.parse::<u32>().ok()) {
                if hour < 6 || hour >= 22 {
                    alerts.push(FraudAlert {
                        alert_type: "TIMING_ANOMALY".to_string(),
                        severity: "MEDIUM".to_string(),
                        title: "After-Hours Approval".to_string(),
                        description: format!("Loan {} approved at {}",
                            record.loan_id.as_deref().unwrap_or("N/A"), time),
                        amount_at_risk: record.amount.unwrap_or(0.0),
                        officer_id: record.officer_id.clone(),
                        loan_ids: record.loan_id.clone().map(|id| vec![id]).unwrap_or_default(),
                        details: serde_json::json!(record),
                    });
                }
            }
        }
    }
}

fn detect_amount_anomalies(data: &[LoanRecord], alerts: &mut Vec<FraudAlert>) {
    let amounts: Vec<f64> = data.iter()
        .filter_map(|r| r.amount)
        .filter(|&a| a > 0.0)
        .collect();

    if amounts.len() < 5 {
        return;
    }

    let mean = amounts.iter().sum::<f64>() / amounts.len() as f64;
    let variance = amounts.iter().map(|a| (a - mean).powi(2)).sum::<f64>() / amounts.len() as f64;
    let std_dev = variance.sqrt();
    let threshold = mean + (2.5 * std_dev);

    for record in data {
        if let Some(amount) = record.amount {
            if amount > threshold {
                let percent_above = ((amount / mean - 1.0) * 100.0) as i32;
                alerts.push(FraudAlert {
                    alert_type: "AMOUNT_ANOMALY".to_string(),
                    severity: "MEDIUM".to_string(),
                    title: "Unusually Large Loan".to_string(),
                    description: format!("Loan amount UGX {:.0} is {}% above average", amount, percent_above),
                    amount_at_risk: amount,
                    officer_id: record.officer_id.clone(),
                    loan_ids: record.loan_id.clone().map(|id| vec![id]).unwrap_or_default(),
                    details: serde_json::json!({
                        "loan": record,
                        "mean": mean,
                        "std_dev": std_dev
                    }),
                });
            }
        }
    }
}

fn calculate_risk_score(alerts: &[FraudAlert]) -> u32 {
    let mut score: u32 = 0;

    for alert in alerts {
        match alert.severity.as_str() {
            "CRITICAL" => score += 25,
            "HIGH" => score += 15,
            "MEDIUM" => score += 8,
            _ => score += 3,
        }
    }

    score.min(100)
}

// ============================================
// UTILITY FUNCTIONS
// ============================================

fn parse_csv_line(line: &str) -> Vec<String> {
    let mut result = Vec::new();
    let mut current = String::new();
    let mut in_quotes = false;

    for c in line.chars() {
        match c {
            '"' => in_quotes = !in_quotes,
            ',' if !in_quotes => {
                result.push(current.trim().to_string());
                current = String::new();
            }
            _ => current.push(c),
        }
    }
    result.push(current.trim().to_string());

    result
}

fn levenshtein_similarity(s1: &str, s2: &str) -> f64 {
    let len1 = s1.len();
    let len2 = s2.len();

    if len1 == 0 && len2 == 0 {
        return 1.0;
    }

    let max_len = len1.max(len2);

    let mut matrix = vec![vec![0; len2 + 1]; len1 + 1];

    for i in 0..=len1 {
        matrix[i][0] = i;
    }
    for j in 0..=len2 {
        matrix[0][j] = j;
    }

    let s1_chars: Vec<char> = s1.chars().collect();
    let s2_chars: Vec<char> = s2.chars().collect();

    for i in 1..=len1 {
        for j in 1..=len2 {
            let cost = if s1_chars[i - 1] == s2_chars[j - 1] { 0 } else { 1 };
            matrix[i][j] = (matrix[i - 1][j] + 1)
                .min(matrix[i][j - 1] + 1)
                .min(matrix[i - 1][j - 1] + cost);
        }
    }

    let distance = matrix[len1][len2];
    (max_len - distance) as f64 / max_len as f64
}

// ============================================
// TESTS
// ============================================

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_string_similarity() {
        assert!(string_similarity("phone", "phone") > 0.99);
        assert!(string_similarity("phone", "phone_number") > 0.5);
        assert!(string_similarity("loan_id", "loanid") > 0.8);
    }

    #[test]
    fn test_csv_parsing() {
        let csv = "name,amount,date\nJohn,1000,2024-01-01\nJane,2000,2024-01-02";
        let result = parse_csv(csv);
        assert!(result.contains("John"));
        assert!(result.contains("1000"));
    }

    #[test]
    fn test_sample_data_generation() {
        let data = generate_sample_data(100);
        let parsed: Vec<serde_json::Value> = serde_json::from_str(&data).unwrap();
        assert_eq!(parsed.len(), 100);
    }
}
